Use upload-core-dumps

diff --git a/.github/workflows/test-setup-ruby-and-rust.yml b/.github/workflows/test-setup-ruby-and-rust.yml
--- a/.github/workflows/test-setup-ruby-and-rust.yml
+++ b/.github/workflows/test-setup-ruby-and-rust.yml
@@ -6,7 +6,9 @@ on:
       - "setup-ruby-and-rust/**/*"
       - ".github/workflows/test-setup-ruby-and-rust.yml"
   workflow_dispatch:
-
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 env:
   SCCACHE_LOG: debug
 jobs:
@@ -25,10 +27,10 @@ jobs:
           - name: "matsadler/magnus"
             slug: magnus
             ref: main
-            run: cargo test -- --nocapture
+            run: cargo test -- --nocapture --skip it_includes_backtrace_in_debug
         os: ["ubuntu-latest", "windows-latest", "macos-latest"]
         rust: ["stable"]
-        ruby: ["3.0", "3.1", "3.2", "3.3"]
+        ruby: ["3.0", "3.1", "3.2", "3.3", "head"]
         cargo-cache: ["true"]
         include:
           - os: "ubuntu-latest"
@@ -61,7 +63,7 @@ jobs:
               name: "matsadler/magnus"
               slug: magnus
               ref: main
-              run: cargo test -- --nocapture || echo "::warning::cargo test failed on mswin"
+              run: cargo test -- --nocapture --skip it_includes_backtrace_in_debug || echo "::warning::cargo test failed on mswin"
 
     runs-on: ${{ matrix.os }}
     steps:
@@ -78,6 +80,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           path: ./tmp/actions
+      - uses: ./tmp/actions/upload-core-dumps
       - uses: ./tmp/actions/setup-ruby-and-rust
         id: setup
         with:
@@ -93,4 +96,11 @@ jobs:
         run: ruby ./tmp/actions/setup-ruby-and-rust/test.rb -v
       - name: Run tests for ${{ matrix.repo.name }}
         shell: bash
-        run: ${{ matrix.repo.run }}
+        run: |
+          : ${{ matrix.repo.run }}
+
+          if [[ "${{runner.os}}" != "Windows" ]]; then
+            ulimit -c unlimited # Enable core dumps
+          fi
+
+          ${{ matrix.repo.run }}
