Always save the install cache by default (#30)

diff --git a/.github/workflows/test-setup-ruby-and-rust.yml b/.github/workflows/test-setup-ruby-and-rust.yml
--- a/.github/workflows/test-setup-ruby-and-rust.yml
+++ b/.github/workflows/test-setup-ruby-and-rust.yml
@@ -40,7 +40,7 @@ jobs:
               name: "oxidize-rb/oxi-test"
               slug: oxi-test
               ref: main
-              run: bundle exec rake || echo "::warning::bundle exec rake failed on mswin"
+              run: bundle exec rake
           - os: "windows-latest"
             ruby: "mswin"
             experimental: true
@@ -50,7 +50,7 @@ jobs:
               name: "oxidize-rb/oxi-test"
               slug: oxi-test
               ref: main
-              run: bundle exec rake
+              run: bundle exec rake || echo "::warning::bundle exec rake failed on mswin"
           - os: "windows-latest"
             slug: magnus
             ruby: "mswin"
@@ -92,4 +92,5 @@ jobs:
           SETUP_OUTPUTS: ${{ toJSON(steps.setup.outputs) }}
         run: ruby ./tmp/actions/setup-ruby-and-rust/test.rb -v
       - name: Run tests for ${{ matrix.repo.name }}
+        shell: bash
         run: ${{ matrix.repo.run }}
