Make mswin infallible on this repo

diff --git a/.github/workflows/test-setup-ruby-and-rust.yml b/.github/workflows/test-setup-ruby-and-rust.yml
--- a/.github/workflows/test-setup-ruby-and-rust.yml
+++ b/.github/workflows/test-setup-ruby-and-rust.yml
@@ -23,7 +23,7 @@ jobs:
           - name: "matsadler/magnus"
             slug: magnus
             ref: main
-            run: cargo test
+            run: cargo test -- --nocapture
         os: ["ubuntu-latest", "windows-latest", "macos-latest"]
         rust: ["stable"]
         ruby: ["3.0", "3.1", "3.2", "3.3"]
@@ -46,7 +46,7 @@ jobs:
               name: "oxidize-rb/oxi-test"
               slug: oxi-test
               ref: main
-              run: bundle exec rake
+              run: bundle exec rake || echo "::warning::rake test failed on ${{ matrix.os }} for ${{ matrix.repo.name }}"
           - os: "windows-latest"
             slug: magnus
             ruby: "mswin"
@@ -56,7 +56,7 @@ jobs:
               name: "matsadler/magnus"
               slug: magnus
               ref: main
-              run: cargo test
+              run: cargo test -- --nocapture || echo "::warning::cargo test failed on ${{ matrix.os }} for ${{ matrix.repo.name }}"
 
     runs-on: ${{ matrix.os }}
     steps:
